// Code generated by protoc-gen-go. DO NOT EDIT.
// source: arachne.proto

package arachne

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameRequest_GameType int32

const (
	GameRequest_RANDOM GameRequest_GameType = 0
	GameRequest_REPLAY GameRequest_GameType = 1
)

var GameRequest_GameType_name = map[int32]string{
	0: "RANDOM",
	1: "REPLAY",
}
var GameRequest_GameType_value = map[string]int32{
	"RANDOM": 0,
	"REPLAY": 1,
}

func (x GameRequest_GameType) String() string {
	return proto.EnumName(GameRequest_GameType_name, int32(x))
}
func (GameRequest_GameType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{0, 0}
}

type GameRequest struct {
	Gametype GameRequest_GameType `protobuf:"varint,1,opt,name=gametype,enum=arachne.GameRequest_GameType" json:"gametype,omitempty"`
	// seed declares the game to be replayed when GameType is REPLAY
	Seed                 int64    `protobuf:"varint,2,opt,name=seed" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameRequest) Reset()         { *m = GameRequest{} }
func (m *GameRequest) String() string { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()    {}
func (*GameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{0}
}
func (m *GameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRequest.Unmarshal(m, b)
}
func (m *GameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRequest.Marshal(b, m, deterministic)
}
func (dst *GameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequest.Merge(dst, src)
}
func (m *GameRequest) XXX_Size() int {
	return xxx_messageInfo_GameRequest.Size(m)
}
func (m *GameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequest proto.InternalMessageInfo

func (m *GameRequest) GetGametype() GameRequest_GameType {
	if m != nil {
		return m.Gametype
	}
	return GameRequest_RANDOM
}

func (m *GameRequest) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

type Game struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Seed                 int64    `protobuf:"varint,2,opt,name=seed" json:"seed,omitempty"`
	CardsRemaining       int32    `protobuf:"varint,3,opt,name=cardsRemaining" json:"cardsRemaining,omitempty"`
	CaptureCount         int32    `protobuf:"varint,4,opt,name=captureCount" json:"captureCount,omitempty"`
	Stack                []*Stack `protobuf:"bytes,5,rep,name=stack" json:"stack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{1}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (dst *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(dst, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Game) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *Game) GetCardsRemaining() int32 {
	if m != nil {
		return m.CardsRemaining
	}
	return 0
}

func (m *Game) GetCaptureCount() int32 {
	if m != nil {
		return m.CaptureCount
	}
	return 0
}

func (m *Game) GetStack() []*Stack {
	if m != nil {
		return m.Stack
	}
	return nil
}

type Stack struct {
	HiddenCount          int32    `protobuf:"varint,1,opt,name=hiddenCount" json:"hiddenCount,omitempty"`
	Cards                []*Card  `protobuf:"bytes,2,rep,name=cards" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stack) Reset()         { *m = Stack{} }
func (m *Stack) String() string { return proto.CompactTextString(m) }
func (*Stack) ProtoMessage()    {}
func (*Stack) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{2}
}
func (m *Stack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stack.Unmarshal(m, b)
}
func (m *Stack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stack.Marshal(b, m, deterministic)
}
func (dst *Stack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stack.Merge(dst, src)
}
func (m *Stack) XXX_Size() int {
	return xxx_messageInfo_Stack.Size(m)
}
func (m *Stack) XXX_DiscardUnknown() {
	xxx_messageInfo_Stack.DiscardUnknown(m)
}

var xxx_messageInfo_Stack proto.InternalMessageInfo

func (m *Stack) GetHiddenCount() int32 {
	if m != nil {
		return m.HiddenCount
	}
	return 0
}

func (m *Stack) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Card struct {
	Suit                 int32    `protobuf:"varint,1,opt,name=suit" json:"suit,omitempty"`
	Rank                 int32    `protobuf:"varint,2,opt,name=rank" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{3}
}
func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (dst *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(dst, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetSuit() int32 {
	if m != nil {
		return m.Suit
	}
	return 0
}

func (m *Card) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type MoveRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FromCol              int32    `protobuf:"varint,2,opt,name=fromCol" json:"fromCol,omitempty"`
	FromRow              int32    `protobuf:"varint,3,opt,name=fromRow" json:"fromRow,omitempty"`
	ToCol                int32    `protobuf:"varint,4,opt,name=toCol" json:"toCol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{4}
}
func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (dst *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(dst, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MoveRequest) GetFromCol() int32 {
	if m != nil {
		return m.FromCol
	}
	return 0
}

func (m *MoveRequest) GetFromRow() int32 {
	if m != nil {
		return m.FromRow
	}
	return 0
}

func (m *MoveRequest) GetToCol() int32 {
	if m != nil {
		return m.ToCol
	}
	return 0
}

type DealRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealRequest) Reset()         { *m = DealRequest{} }
func (m *DealRequest) String() string { return proto.CompactTextString(m) }
func (*DealRequest) ProtoMessage()    {}
func (*DealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{5}
}
func (m *DealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealRequest.Unmarshal(m, b)
}
func (m *DealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealRequest.Marshal(b, m, deterministic)
}
func (dst *DealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealRequest.Merge(dst, src)
}
func (m *DealRequest) XXX_Size() int {
	return xxx_messageInfo_DealRequest.Size(m)
}
func (m *DealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealRequest proto.InternalMessageInfo

func (m *DealRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EndGameRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndGameRequest) Reset()         { *m = EndGameRequest{} }
func (m *EndGameRequest) String() string { return proto.CompactTextString(m) }
func (*EndGameRequest) ProtoMessage()    {}
func (*EndGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{6}
}
func (m *EndGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndGameRequest.Unmarshal(m, b)
}
func (m *EndGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndGameRequest.Marshal(b, m, deterministic)
}
func (dst *EndGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndGameRequest.Merge(dst, src)
}
func (m *EndGameRequest) XXX_Size() int {
	return xxx_messageInfo_EndGameRequest.Size(m)
}
func (m *EndGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndGameRequest proto.InternalMessageInfo

func (m *EndGameRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EndGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndGameResponse) Reset()         { *m = EndGameResponse{} }
func (m *EndGameResponse) String() string { return proto.CompactTextString(m) }
func (*EndGameResponse) ProtoMessage()    {}
func (*EndGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_arachne_e1077b6270f1a69b, []int{7}
}
func (m *EndGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndGameResponse.Unmarshal(m, b)
}
func (m *EndGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndGameResponse.Marshal(b, m, deterministic)
}
func (dst *EndGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndGameResponse.Merge(dst, src)
}
func (m *EndGameResponse) XXX_Size() int {
	return xxx_messageInfo_EndGameResponse.Size(m)
}
func (m *EndGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndGameResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GameRequest)(nil), "arachne.GameRequest")
	proto.RegisterType((*Game)(nil), "arachne.Game")
	proto.RegisterType((*Stack)(nil), "arachne.Stack")
	proto.RegisterType((*Card)(nil), "arachne.Card")
	proto.RegisterType((*MoveRequest)(nil), "arachne.MoveRequest")
	proto.RegisterType((*DealRequest)(nil), "arachne.DealRequest")
	proto.RegisterType((*EndGameRequest)(nil), "arachne.EndGameRequest")
	proto.RegisterType((*EndGameResponse)(nil), "arachne.EndGameResponse")
	proto.RegisterEnum("arachne.GameRequest_GameType", GameRequest_GameType_name, GameRequest_GameType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArachneClient is the client API for Arachne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArachneClient interface {
	// StartGame starts a new game
	StartGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Game, error)
	// RequestMove requests a move of cards
	RequestMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*Game, error)
	// RequestDeal requests a deal
	RequestDeal(ctx context.Context, in *DealRequest, opts ...grpc.CallOption) (*Game, error)
	// EndGame requests the end of a game
	EndGame(ctx context.Context, in *EndGameRequest, opts ...grpc.CallOption) (*EndGameResponse, error)
}

type arachneClient struct {
	cc *grpc.ClientConn
}

func NewArachneClient(cc *grpc.ClientConn) ArachneClient {
	return &arachneClient{cc}
}

func (c *arachneClient) StartGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/arachne.Arachne/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arachneClient) RequestMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/arachne.Arachne/RequestMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arachneClient) RequestDeal(ctx context.Context, in *DealRequest, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/arachne.Arachne/RequestDeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arachneClient) EndGame(ctx context.Context, in *EndGameRequest, opts ...grpc.CallOption) (*EndGameResponse, error) {
	out := new(EndGameResponse)
	err := c.cc.Invoke(ctx, "/arachne.Arachne/EndGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArachneServer is the server API for Arachne service.
type ArachneServer interface {
	// StartGame starts a new game
	StartGame(context.Context, *GameRequest) (*Game, error)
	// RequestMove requests a move of cards
	RequestMove(context.Context, *MoveRequest) (*Game, error)
	// RequestDeal requests a deal
	RequestDeal(context.Context, *DealRequest) (*Game, error)
	// EndGame requests the end of a game
	EndGame(context.Context, *EndGameRequest) (*EndGameResponse, error)
}

func RegisterArachneServer(s *grpc.Server, srv ArachneServer) {
	s.RegisterService(&_Arachne_serviceDesc, srv)
}

func _Arachne_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArachneServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arachne.Arachne/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArachneServer).StartGame(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arachne_RequestMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArachneServer).RequestMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arachne.Arachne/RequestMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArachneServer).RequestMove(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arachne_RequestDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArachneServer).RequestDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arachne.Arachne/RequestDeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArachneServer).RequestDeal(ctx, req.(*DealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arachne_EndGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArachneServer).EndGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arachne.Arachne/EndGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArachneServer).EndGame(ctx, req.(*EndGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Arachne_serviceDesc = grpc.ServiceDesc{
	ServiceName: "arachne.Arachne",
	HandlerType: (*ArachneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _Arachne_StartGame_Handler,
		},
		{
			MethodName: "RequestMove",
			Handler:    _Arachne_RequestMove_Handler,
		},
		{
			MethodName: "RequestDeal",
			Handler:    _Arachne_RequestDeal_Handler,
		},
		{
			MethodName: "EndGame",
			Handler:    _Arachne_EndGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arachne.proto",
}

func init() { proto.RegisterFile("arachne.proto", fileDescriptor_arachne_e1077b6270f1a69b) }

var fileDescriptor_arachne_e1077b6270f1a69b = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xad, 0xdb, 0x66, 0x1d, 0x37, 0xb4, 0x1b, 0xd6, 0x24, 0xa2, 0xa1, 0x49, 0x91, 0x41, 0xa8,
	0x4f, 0x11, 0x2a, 0xbc, 0xf0, 0x82, 0xd4, 0x75, 0xd3, 0x5e, 0xd8, 0xa8, 0x3c, 0x5e, 0x78, 0x34,
	0xf1, 0x25, 0x8b, 0xd6, 0xc4, 0xc1, 0x71, 0x80, 0xbd, 0xf1, 0x43, 0xf8, 0x83, 0xfc, 0x0b, 0x64,
	0xe7, 0x43, 0x69, 0x37, 0xf6, 0x76, 0xee, 0xbd, 0xe7, 0xdc, 0xe4, 0x1c, 0xdb, 0x30, 0x15, 0x5a,
	0xc4, 0x37, 0x39, 0x46, 0x85, 0x56, 0x46, 0xd1, 0x49, 0x53, 0xb2, 0xdf, 0x04, 0xfc, 0x0b, 0x91,
	0x21, 0xc7, 0xef, 0x15, 0x96, 0x86, 0xbe, 0x87, 0xfd, 0x44, 0x64, 0x68, 0xee, 0x0a, 0x0c, 0x48,
	0x48, 0xe6, 0xb3, 0xc5, 0x49, 0xd4, 0x4a, 0x7b, 0x3c, 0x87, 0x3f, 0xdf, 0x15, 0xc8, 0x3b, 0x3a,
	0xa5, 0x30, 0x2e, 0x11, 0x65, 0x30, 0x0c, 0xc9, 0x7c, 0xc4, 0x1d, 0x66, 0x0c, 0xf6, 0x5b, 0x26,
	0x05, 0xd8, 0xe3, 0xcb, 0xab, 0xb3, 0x4f, 0x97, 0x87, 0x03, 0x87, 0xcf, 0xd7, 0x1f, 0x97, 0x5f,
	0x0e, 0x09, 0xfb, 0x43, 0x60, 0x6c, 0x49, 0x74, 0x06, 0xc3, 0x54, 0xba, 0xaf, 0x8e, 0xf8, 0x30,
	0x95, 0x0f, 0x2d, 0xa4, 0xaf, 0x61, 0x16, 0x0b, 0x2d, 0x4b, 0x8e, 0x99, 0x48, 0xf3, 0x34, 0x4f,
	0x82, 0x51, 0x48, 0xe6, 0x1e, 0xdf, 0xe9, 0x52, 0x06, 0x4f, 0x63, 0x51, 0x98, 0x4a, 0xe3, 0x4a,
	0x55, 0xb9, 0x09, 0xc6, 0x8e, 0xb5, 0xd5, 0xa3, 0xaf, 0xc0, 0x2b, 0x8d, 0x88, 0x6f, 0x03, 0x2f,
	0x1c, 0xcd, 0xfd, 0xc5, 0xac, 0x33, 0x7a, 0x6d, 0xbb, 0xbc, 0x1e, 0xb2, 0x2b, 0xf0, 0x5c, 0x4d,
	0x43, 0xf0, 0x6f, 0x52, 0x29, 0x31, 0xaf, 0x37, 0x12, 0xb7, 0xb1, 0xdf, 0xa2, 0x2f, 0xc1, 0x73,
	0xbf, 0x11, 0x0c, 0xdd, 0xc2, 0x69, 0xb7, 0x70, 0x25, 0xb4, 0xe4, 0xf5, 0x8c, 0x45, 0x30, 0xb6,
	0xa5, 0x73, 0x57, 0xa5, 0xed, 0x1e, 0x87, 0x6d, 0x4f, 0x8b, 0xfc, 0xd6, 0x39, 0xf6, 0xb8, 0xc3,
	0x2c, 0x01, 0xff, 0x52, 0xfd, 0xe8, 0x0e, 0x68, 0x37, 0xa4, 0x00, 0x26, 0xdf, 0xb4, 0xca, 0x56,
	0x6a, 0xd3, 0xa8, 0xda, 0xb2, 0x9d, 0x70, 0xf5, 0xb3, 0xc9, 0xa8, 0x2d, 0xe9, 0x11, 0x78, 0x46,
	0x59, 0x45, 0x9d, 0x4a, 0x5d, 0xb0, 0x13, 0xf0, 0xcf, 0x50, 0x6c, 0xfe, 0xf3, 0x21, 0x16, 0xc2,
	0xec, 0x3c, 0x97, 0xfd, 0xbb, 0xb2, 0xcb, 0x78, 0x06, 0x07, 0x1d, 0xa3, 0x2c, 0x54, 0x5e, 0xe2,
	0xe2, 0x2f, 0x81, 0xc9, 0xb2, 0x0e, 0x81, 0x2e, 0xe0, 0xc9, 0xb5, 0x11, 0xda, 0xb8, 0xb3, 0x3e,
	0x7a, 0xe8, 0x56, 0x1d, 0x4f, 0xb7, 0xba, 0x6c, 0x40, 0xdf, 0x81, 0xdf, 0xcc, 0x6c, 0x06, 0x3d,
	0x55, 0x2f, 0x92, 0xc7, 0x54, 0xd6, 0x50, 0x4f, 0xd5, 0xf3, 0x77, 0x5f, 0xf5, 0x01, 0x26, 0xcd,
	0xef, 0xd3, 0xe7, 0xdd, 0x6c, 0xdb, 0xf2, 0x71, 0x70, 0x7f, 0x50, 0x3b, 0x65, 0x83, 0xd3, 0x37,
	0xf0, 0x22, 0x55, 0x51, 0xa2, 0x8b, 0x38, 0xc2, 0x5f, 0x22, 0x2b, 0x36, 0x58, 0x46, 0x5a, 0x55,
	0x06, 0x93, 0x2a, 0x95, 0x78, 0x7a, 0xc0, 0x2d, 0xbe, 0xb0, 0x78, 0x6d, 0xdf, 0xe0, 0x9a, 0x7c,
	0xdd, 0x73, 0x8f, 0xf1, 0xed, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x15, 0xb0, 0x9f, 0x9d,
	0x03, 0x00, 0x00,
}
